# Generated by Django 3.1.1 on 2020-09-28 12:12

from django.db import migrations, models
import django.utils.timezone
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200927_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videomaterial',
            name='video_url',
        ),
        migrations.AddField(
            model_name='videomaterial',
            name='video',
            field=embed_video.fields.EmbedVideoField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(null=True, upload_to='profilepics'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='image',
            field=models.ImageField(default='profilepics/default.jpg', upload_to='profilepics'),
        ),
    ]
