# Generated by Django 3.1.1 on 2020-09-28 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200928_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomaterial',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.course'),
        ),
    ]
